version: '3'

networks:
  inception:
    name: inception

services:

  nginx:
    container_name: nginx
    image: nginx:mine
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    
  wordpress:
    container_name: wordpress
    image: wordpress:mine
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:mine
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ./home/vguttenb/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ./home/vguttenb/data/wordpress
      o: bind
      type: none
